name: Deploy to production

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::050451698486:role/github-actions-ecr-role
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Load secrets and add to app.env
        run: aws secretsmanager get-secret-value --secret-id neo_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: neobank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t latest
          docker push -a $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.0 " # default is latest stable
        id: install

      - name: Setup Kops
        uses: hiberbee/github-action-kops@latest
        with:
          command: export kubecfg --admin=24h
          cluster-name: neobank.k8s.local
          state-store: s3://neobank-state-store

      - name: Deploy image to Kops Cluster
        run: kuebctl apply -f k8s/deployment.yaml
